### ISSUE TITLE
Zend\Filter\File\RenameUpload behaves differently when folder exists and not

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-filter#13]
code example:

``` php
$filter = new \Zend\Filter\File\RenameUpload([
    'target' => './public/img/logotypes/logo',
    'use_upload_extension' => true,
    'randomize' => true,
]);
$file = $filter->filter($file_data);
echo $file['tmp_name'];
```

 when `logo` folder exists returned value would be:

```
./public/img/logotypes/logo/phpj7GsVi_55f03311ed828.jpg
```

when `logo` folder doesn't exists returned value would be:

```
./public/img/logotypes/logo_55f034e642bf3.jpg
```

I can't beleave this is desired behavior because this can lead to bugs.
Guess I used this incorrectly because I wanted logo prefix this worked for me until someone created logo folder then everything gone bad :(

---

Originally posted by @svycka at https://github.com/zendframework/zend-filter/issues/4

**Comment by weierophinney** [comment]
@svycka I've checked it and I believe _it is_ desired behaviour. As target we can provide the directory or the file name and in script we can't recognise what you have on mind. So:
- if provided string is a directory (so must exist) then the file will be moved into that directory,
- otherwise, path does not exist, so script assumes that it should be a file



---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-filter/issues/4#issuecomment-522274937

**Comment by weierophinney** [comment]
@webimpress I do not agree with you
> if provided string is a directory (so must exist) then the file will be moved into that directory,

sounds ok.

> otherwise, path does not exist, so script assumes that it should be a file

this is not documented so I am not sure how you decided this is the desired behavior. Don't understand how having two hidden behaviors from one option is good. maybe new `file_prefix` or something would be better.

---

Originally posted by @svycka at https://github.com/zendframework/zend-filter/issues/4#issuecomment-522426808

**Comment by weierophinney** [comment]
@svycka Ok, reopening. Feel free to submit PR - either: documentation update of propose a fix.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-filter/issues/4#issuecomment-522437791

**Comment by weierophinney** [comment]
fixing would mean BC break? if this is the desired behavior

---

Originally posted by @svycka at https://github.com/zendframework/zend-filter/issues/4#issuecomment-522448812

**Comment by weierophinney** [comment]
@svycka If you propose fix which will be BC Break we will plan it for v3.

I've described what is the current behaviour, and, yes, I can see it can be a bit tricky, but _I think_ it is logical. There is not anything like 'file prefix' right now, the provided target is either directory "where file should be moved" or the new file name. As you are using `randomize=true` there is randomized string added to the name.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-filter/issues/4#issuecomment-522450622

**Comment by gsteel** [comment]
Closing as stale
