### ISSUE TITLE
Drop dependency on Laminas\i18n

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-filter#130]
The depenency on laminas-i18n is problematic because it is cyclic in nature - this makes it infeasible to upgrade SMv4 for a start.

The dependency (in dev) is added so that we can auto-wire filters that are shipped with i18n (Symbols are referenced in src). At the moment, users can install `filter` without `i18n` but it makes more sense to me to configure filters present in `i18n` in that library, not here.

**Comment by froschdesign** [comment]
And the filters are already included in the laminas-i18n config provider:

- https://github.com/laminas/laminas-i18n/blob/01738410cb263994d1d192861f642387e7e12ace/src/ConfigProvider.php#L31
- https://github.com/laminas/laminas-i18n/blob/01738410cb263994d1d192861f642387e7e12ace/src/ConfigProvider.php#L62-L95

**Comment by gsteel** [comment]
Thanks @froschdesign - That makes it easier!

**Comment by gsteel** [comment]
Closed via #134
