### ISSUE TITLE
documentation still mentions zendframework

### ISSUE THREAD

**Issue by phil-davis** [laminas/laminas-filter#14]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

https://docs.laminas.dev/laminas-filter/

Instructions and links mention zendframework/laminas-filter

#### Current behavior

Instructions and links mention zendframework/laminas-filter

#### Expected behavior

Instructions and links should mention laminas/laminas-filter

**Comment by michalbundyra** [comment]
See: https://github.com/laminas/documentation-theme/pull/2

**Comment by michalbundyra** [comment]
Solved.
