### ISSUE TITLE
DateTimeFormatter: Add option to return invalid date string unfiltered

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-filter#2]
* add documentation for DateTimeFormatter. Addresses #58.
* add @todo notation in docblock for `$format` property
* add tests for new option

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
```php
$filter = new DateTimeFormatter();
$filter->filter('2013-31-31'); // throws exception
```
  - [x] Detail the original, incorrect behavior.
`DateTimeFormatter::filter` throws an exception in the event that the input is not a parsable date string
  - [x] Detail the new, expected behavior.
```php
$filter = new DateTimeFormatter();
$filter->setThrowInvalidDateException(false);
$filter->filter('2013-31-31'); // returns "2013-31-31"
```
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [x] Add a `CHANGELOG.md` entry for the fix.

---

Originally posted by @marcguyer at https://github.com/zendframework/zend-filter/pull/84

**Comment by weierophinney** [comment]
@marcguyer  This is a new feature because [the exception was previously a desired result](https://github.com/zendframework/zend-filter/blob/922fe11b1595f681ef9618f630ec090070bbf53d/test/DateTimeFormatterTest.php#L119-L125). Please use the `develop` branch instead.

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-filter/pull/84#issuecomment-473177082

**Comment by gsteel** [comment]
This issue and its old PR is pretty stale - in 3.0 the behaviour is the same as the 2.x series so if anyone wants to implement the optional behaviour change, its best to target 3.0 now.

Ref #160
