### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-filter#34]
I was wondering if PHP 8.1 support is planned for laminas-filter. At the moment I'm getting a lot of deprecated warnings:
```
PHP Deprecated:  Return type of Laminas\InputFilter\BaseInputFilter::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\laminas\laminas-inputfilter\src\BaseInputFilter.php on line 70
PHP Deprecated:  Return type of Laminas\Filter\FilterChain::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\laminas\laminas-filter\src\FilterChain.php on line 92
```

**Comment by Ocramius** [comment]
@matbech we've done literally hundreds of component upgrades to 8.1: this one simply seems to be missing.

We also don't don't 8.1 compatibility yet:

https://github.com/laminas/laminas-filter/blob/0fc5dcd27dc22dba1a2544123684c67768fc5f88/composer.json#L28

I suggest checking any other library we've upgraded here so far, then contributing your part with a patch that brings in 8.1 support yourself 👍

**Comment by driehle** [comment]
There is a dependency in `require-dev` which currently hinders the upgrade to PHP 8.1:

```bash
$ composer why-not php 8.1
laminas/laminas-crypt  3.4.0  requires  php (^7.3 || ~8.0.0)
```

There is already a PR pending on laminas-crypt: https://github.com/laminas/laminas-crypt/pull/14

**Comment by driehle** [comment]
With the release of laminas-crypt 3.5.0 supporting PHP 8.1, I have now created PR #35.
