### ISSUE TITLE
Non-string scalar types produce a fatal error with StripNewlines

### ISSUE THREAD

**Issue by internalsystemerror** [laminas/laminas-filter#41]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.13.0

#### Summary

On PHP 7.4, `str_replace` would accept any scalar value and implicitly cast it to a string (even with `declare(strict_types=1)`). As of PHP 8.0, anything but `string|array` to the 3rd argument of `str_replace` throws a fatal error.

See: https://3v4l.org/YOktG

With the PHP 8.1 release, `declare(strict_types=1)` was added to all files (presumably due to the coding standard) meaning that previously valid values passed to `StripNewLines` are now throwing a fatal error.

#### Current behavior

`StripNewLines::filter(123)` throws a fatal error on the latest version whereas previously, it would be implicitly cast to a string.

#### How to reproduce

I intend to submit a PR to introduce failing tests along with a fix.

#### Expected behavior

Previously working values should not throw a fatal error.

**Comment by Ocramius** [comment]
The declaration says that it accepts `string|array` though, not `mixed` :thinking_face:

https://github.com/laminas/laminas-filter/blob/29db2ddc0671d7a250454a466f56922d12d4b255/src/StripNewlines.php#L18-L19

I think we should adjust it to allow `mixed`, then filter only what is filterable?

From `AbstractFilter`, I can see that this is completely broken/wrong:

https://github.com/laminas/laminas-filter/blob/29db2ddc0671d7a250454a466f56922d12d4b255/src/AbstractFilter.php#L84-L96

**Comment by internalsystemerror** [comment]
> The declaration says that it accepts `string|array` though, not `mixed` :thinking_face:

> I think we should adjust it to allow `mixed`, then filter only what is filterable?

This is approach taken in the PR, to expect `$value` to be mixed.

**Comment by Ocramius** [comment]
Linking the PR, since I hadn't seen it before :D 

https://github.com/laminas/laminas-filter/pull/42

**Comment by internalsystemerror** [comment]
@Ocramius this is because you are a very busy person and your time is precious. This issue is mentioned in the description of the PR, so they should already be linked but thank you.

**Comment by Ocramius** [comment]
Sitting in boring meetings, so it isn't too bad :P

**Comment by Ocramius** [comment]
Handled in #42
