### ISSUE TITLE
Is `DateTimeFormatter` filter missed in documentation?

### ISSUE THREAD

**Issue by tempfirstuser** [laminas/laminas-filter#44]
Is `DateTimeFormatter` filter ( https://github.com/laminas/laminas-filter/blob/2.14.x/src/DateTimeFormatter.php ) missed in documentation? At least I wasn't able to find it here https://docs.laminas.dev/laminas-filter/  .

**Comment by froschdesign** [comment]
@tempfirstuser
Unfortunately yes: https://github.com/laminas/laminas-filter/search?q=DateTimeFormatter

**Comment by froschdesign** [comment]
Fixed with #160
