### ISSUE TITLE
Declaration of  Laminas\Filter\FilterPluginManager::get($name, ?array $options = NULL)  must be compatible with  Laminas\ServiceManager\AbstractPluginManager::get($name, $options =  Array, $usePeeringServiceManagers = true)

### ISSUE THREAD

**Issue by grojanteam** [laminas/laminas-filter#56]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.15.0

#### Summary

`Fatal error: Declaration of 
Laminas\Filter\FilterPluginManager::get($name, ?array $options = NULL) 
must be compatible with 
Laminas\ServiceManager\AbstractPluginManager::get($name, $options = 
Array, $usePeeringServiceManagers = true) in 
/app/vendor/laminas/laminas-filter/src/FilterPluginManager.php on line 
521`

#### Current behavior

Compilation Failed

#### How to reproduce

Version of laminas/laminas-filter (2.15.0)
Version of laminas/laminas-servicemanager (2.7.11)

#### Expected behavior

No error

**Comment by grojanteam** [comment]
Relates to https://github.com/laminas/laminas-filter/pull/52/files#diff-c78c2ea795407f22cfd0ad4519b957fb8dd6ff732086e45e74978ac14b6643b0R521

**Comment by fredww** [comment]
I was encountered the same issue as yours

**Comment by grojanteam** [comment]
from my POV 2.15.0 should have dependencies in require to have at least ^3.0 for laminas/laminas-servicemanager

**Comment by cmuench** [comment]
Same here: https://github.com/netz98/n98-magerun2/runs/7300986532?check_suite_focus=true

**Comment by gsteel** [comment]
Service manager is currently only a dev-dependency and you're right, this package should drop support for service manager ^2.

@Ocramius - WDYT to a patch release removing `get` and a minor bump to require SM ^3

**Comment by Ocramius** [comment]
@gsteel IMO:

 1. Revert with dependencies as-is in a patch (and expanded baseline)
 2. Bump + re-add in a minor

**Comment by grojanteam** [comment]
Testing if problem resolved

**Comment by Ocramius** [comment]
Should be fine on `2.15.1`

**Comment by grojanteam** [comment]
@Ocramius yep looks fixed, thanks for fast resolve issue

**Comment by cmuench** [comment]
@Ocramius Can confirm that the issue is fixed for n98-magerun2, too.
