### ISSUE TITLE
ToString filter missing?

### ISSUE THREAD

**Issue by vaclavvanik** [laminas/laminas-filter#98]
### Feature Request

Laminas-filter component has [ToFloat](/laminas/laminas-filter/blob/2.32.x/src/ToFloat.php), [ToInt](/laminas/laminas-filter/blob/2.32.x/src/ToInt.php) and [ToNull](/laminas/laminas-filter/blob/2.32.x/src/ToFloat.php) filters but `ToString` is missing.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

This filter should be similar as `ToInt`:

```php
class ToString extends AbstractFilter
{
    public function filter($value)
    {
        if (
            is_scalar($value)
            || $value === null
            || $value instanceof Stringable
        ) {
            return (string)  $value;
        }

        return $value;
    }
}
```

Your opinions?

**Comment by Ocramius** [comment]
Send a patch with tests and it shall be added 👍
